Capstone project
the-faizmohammad/conferencePage pull request #1
Opened 2023-07-07 03:58 UTC by the-faizmohammad

This pull request introduces several additions to the project. The following sections have been added:

Build Only These 2 Pages:

Home Page: Created a responsive version for two different screen sizes.
About Page: Developed a responsive version for two different screen sizes.
Page Navigation:

Home Page Link: Added a link to the About page in the menu.
Logo Link: Enabled the logo in the header to redirect to the Home page.
Mobile Menu:

Close Button: Implemented a close (X) button that allows users to close the mobile menu.
Dynamic Section:

Featured Speakers: Utilized JavaScript to dynamically generate the "Featured speakers" section.
Project Description: Included a detailed description of the project.

Additionally, the project has been successfully deployed.

These changes enhance the user experience by providing responsive designs for different screen sizes, improving navigation through menu links, adding a mobile menu with a close button, dynamically generating content, and ensuring the project is ready for deployment.

2023-07-07 06:51 UTC, Ibizugbe requested changes
Hi @the-faizmohammad 👋👋, 

![tryagain](https://github.com/the-faizmohammad/conferencePage/assets/64643995/d03ed03b-9a74-4292-a424-00c9dbc2abd6)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Project has a `home` and `about` page and there's a link to navigate between both pages👍.
- [x] Both pages contain the same nave bar and footer👍.
- [x] On mobile it has a hamburger menu on the left👍.
- [x] The page uses the right color and font family and stated in the design👍.
- [x] All images have an `alt` value👍.
- [x] The logo has a hyperlink to the home page👍.
- [x] The speaker section is generated dynamically👍.
- [x] Nice job implementing the functionalities of the more button👍.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] Try to ensure your commit messages are always capitalized as this is more professional 😉.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 06:51 UTC, Ibizugbe commented on README.md
> +- [Live Demo link](https://https://the-faizmohammad.github.io/conferencePage/)
The link to your live demo is currently broken.
<img width="607" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/e3675139-3863-430c-a18e-cca6c35b37d7">

Kindly deploy your project using GitHub pages and update the live demo with the link to the project as this is a requirement in this milestone😉.

2023-07-07 06:51 UTC, Ibizugbe commented on index.html
> +            </nav>
Nice job wrapping your navigation links in a `nav` tag and your `nav` tag in a `header` tag as this is a good semantic practice😉.  But let's try to stick to the design by ensuring the Nav is transparent on mobile😉. Kindly take away the white background on the `nav` and make it match the design😉.


| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img width="400" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/ed785e7c-3fa6-4cf1-a4bc-43d18f08edeb">|<img width="400" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/15a89147-aebc-4bdb-ab22-18e1305335df">|

2023-07-07 06:51 UTC, Ibizugbe commented on index.html
> +                <a class="bottom-nav-link enroll" href="#"><strong>Buy Ticket</strong></a>
The `Buy Tickets` link is not properly aligned to the center to match the design, I suggest you kindly fix that as we are required to stick to the design even as we personalize the project👍.

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img width="350" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/51c858ee-9070-44f9-a4b9-f841f86297c6">|<img width="350" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/adfdc93a-dd18-407d-9443-bd2c6e185e5f">|

2023-07-07 06:51 UTC, Ibizugbe commented on index.html
> +          </div>
Your navigation bar on the `home` page is blurred as a result of the kind of background image you used for the header😉. and this doesn't match the design. Kindly ensure your nav bar is built to match the given design👍.

yours
![image](https://github.com/the-faizmohammad/conferencePage/assets/64643995/6e67089d-24c8-4c39-9609-3f544fab466c)

design
<img width="583" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/7cecd798-1791-4f43-a87d-b84e59c4c55f">

2023-07-07 06:51 UTC, Ibizugbe commented on index.html
> +      </div>
To make your page more semantic, Kindly take these welcome texts away from the header section😉. I suggest the header should only contain the nav and elements relating to navigations😉.  You can probably create an `intro` section with a section tag after the header and put these contents inside it👍.

2023-07-07 06:51 UTC, Ibizugbe commented on index.html
> +    <h3 class="program-title"><strong>Main Program</strong></h3>
Nice job so far obeying semantic rules (there is only one `h1` on each page😉). To stay consistent with the header hierarchy rule, let's ensure every other section starts with an `h2` and the subsequent header can follow the next hierarchy😉. Kindly implement this all round your project👍.

2023-07-07 06:51 UTC, Ibizugbe commented on index.html
> +    <h3 class="program-title"><strong>Main Program</strong></h3>
To match the design, Let's try to implement this underline style in every header where it is required in our project as shown in the design😉.

<img width="311" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/75451004-95df-4b37-8b85-ed02a81c5320">

I can see you implemented it in the partner section of your index page, kindly implement it in other required places😉.

2023-07-07 06:51 UTC, Ibizugbe commented on index.html
> +  </section>
Kindly ensure the right spacings are added around the images to match the design as this is a requirement in this milestone😉.

design
<img width="721" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/0c210c2a-d58b-4e15-9161-0e822f317a28">

yours
<img width="960" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/1e44d8fd-b611-468a-97da-e0d6f79f8399">

2023-07-07 06:51 UTC, Ibizugbe commented on index.html
> +</div>
Both for your index and about page, I suggest you kindly wrap the footer section in a `footer` tag as this is more semantic😉. also, to match the design, kindly do well to add the necessary spacings (margin and padding)

design
<img width="697" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/cf0b5ce4-ce20-4864-a5dc-060730f8cd98">

Yours
<img width="950" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/9c8eaa12-74b4-419b-9ee0-fd5bdc3f316c">

Kindly implement these changes in both your index and about page👍.

2023-07-07 06:51 UTC, Ibizugbe commented on index.html
> +     </div>
On mobile, your partner images should be properly aligned to match the given design as it is a requirement in this milestone that we stick to the given design😉.

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img width="323" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/2d8fd3b7-4363-4729-9f10-ca5d5766c12e">|<img width="319" alt="image" src="https://github.com/the-faizmohammad/conferencePage/assets/64643995/12666484-1afb-43c4-a19a-c1a28ac85ecb">|

2023-07-08 01:44 UTC, LionRouge1 approved these changes
Hi @the-faizmohammad, 

# STATUS: APPROVED! 🥇 💯 
Great work on making the changes 👏 
You've done well implementing the requested changes

![done](https://media.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif)

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-07-08 01:44 UTC, LionRouge1 commented on index.html
> +    <h2 class="program-title"><strong>Main Program</strong></h2>
- [OPTIONAL] As mentioned by the previous reviewer. Kindly add the red line under the titles to match the Figma design.
<img width="311" alt="251657352-75451004-95df-4b37-8b85-ed02a81c5320" src="https://github.com/the-faizmohammad/conferencePage/assets/91142432/6626287b-37e6-470f-8dd8-e52805bf8369">

2023-07-08 19:17 UTC, merged